[package]
name = "shspectr"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
default = ["web"]
web = ["dep:shspectr-web"]

[dependencies]
shspectr-common = { path = "../shspectr-common", features = ["std"] }
shspectr-web = { path = "../shspectr-web", optional = true }
anyhow = "1"
aya = "0.13.1"
aya-log = "0.2.1"
clap = { version = "4", features = ["derive"] }
include_bytes_aligned = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
libc = "0.2"
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "signal"] }
bytes = "1"
rusqlite = { version = "0.35", features = ["bundled"] }
serde_json = "1"
tokio-util = "0.7.18"
