[package]
name = "shspectr"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
default = ["web"]
web = ["dep:shspectr-web"]

[dependencies]
shspectr-common = { path = "../shspectr-common", features = ["std"] }
shspectr-web = { path = "../shspectr-web", optional = true }
anyhow.workspace = true
aya = "0.13.1"
clap.workspace = true
include_bytes_aligned = "0.1"
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["json"] }
libc = "0.2"
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "signal"] }
rusqlite.workspace = true
serde_json.workspace = true
tokio-util = "0.7.18"
getrandom = "0.3"
