#![no_std]
#![no_main]
#![allow(deprecated)] // bpf_probe_read_user_str is simpler for fixed-size buffers
#![allow(clippy::needless_pass_by_value)] // aya macro requires owned TracePointContext

use aya_ebpf::{
    helpers::{
        bpf_get_current_comm, bpf_get_current_pid_tgid, bpf_get_current_uid_gid,
        bpf_probe_read_kernel,
    },
    macros::{map, tracepoint},
    maps::{Array, HashMap, RingBuf},
    programs::TracePointContext,
};
use aya_ebpf_bindings::helpers::{
    bpf_get_current_cgroup_id, bpf_get_current_task, bpf_ktime_get_ns,
};
use shspectr_common::{
    EventHeader, EventType, ExecEvent, ExitEvent, IoEvent, MAX_ARGV_COUNT, MAX_DATA_LEN, offset_idx,
};

#[map]
static EVENTS: RingBuf = RingBuf::with_byte_size(256 * 1024, 0);

/// Pending exec events keyed by pid_tgid, filled on sys_enter_execve
/// and consumed on sys_exit_execve.
#[map]
static PENDING_EXEC: HashMap<u64, ExecEvent> = HashMap::with_max_entries(1024, 0);

/// Per-CPU scratch space for building an [`ExecEvent`] without
/// exceeding the 512-byte BPF stack limit.
#[map]
static EXEC_SCRATCH: aya_ebpf::maps::PerCpuArray<ExecEvent> =
    aya_ebpf::maps::PerCpuArray::with_max_entries(1, 0);

/// Single-element array map populated by userspace with BTF-resolved offsets.
#[map]
static OFFSETS: Array<u64> = Array::with_max_entries(offset_idx::COUNT, 0);

/// Info stashed on sys_enter_read, consumed on sys_exit_read.
/// Keyed by pid_tgid.
#[repr(C)]
struct PendingRead {
    fd: u32,
    _pad: u32,
    buf_ptr: u64,
    count: u64,
}

#[map]
static PENDING_READ: HashMap<u64, PendingRead> = HashMap::with_max_entries(1024, 0);

/// Info stashed on sys_enter_write, consumed on sys_exit_write.
/// Keyed by pid_tgid.
#[repr(C)]
struct PendingWrite {
    fd: u32,
    _pad: u32,
    buf_ptr: u64,
    count: u64,
}

#[map]
static PENDING_WRITE: HashMap<u64, PendingWrite> = HashMap::with_max_entries(1024, 0);

/// Set of tgids that have been seen via a successful execve.
/// I/O events are only captured for processes in this set, which
/// excludes pre-existing processes like terminal multiplexers.
#[map]
static EXEC_PIDS: HashMap<u32, u64> = HashMap::with_max_entries(4096, 0);

/// Single-element array map holding the tgid of the shspectr process itself.
/// Used to skip events generated by shspectr's own I/O (avoids feedback loops).
#[map]
static SELF_TGID: Array<u32> = Array::with_max_entries(1, 0);

/// Returns `Some(pid_tgid)` if the current task is NOT the shspectr process,
/// or `None` if it is (meaning the caller should skip processing).
fn check_not_self() -> Option<u64> {
    let pid_tgid = bpf_get_current_pid_tgid();
    let tgid = (pid_tgid >> 32) as u32;
    if SELF_TGID.get(0).copied() == Some(tgid) {
        None
    } else {
        Some(pid_tgid)
    }
}

/// Read a u64 offset value from the OFFSETS map.
fn get_offset(idx: u32) -> u64 {
    OFFSETS.get(idx).copied().unwrap_or(0)
}

/// Read a pointer-sized value from a kernel address at a given byte offset.
///
/// # Safety
///
/// `base` must be a valid kernel pointer and `offset` must point to a
/// pointer-sized field within the object.
unsafe fn read_ptr(base: u64, offset: u64) -> Result<u64, i64> {
    let addr = (base + offset) as *const u64;
    // SAFETY: caller guarantees base+offset points to a valid kernel pointer field.
    unsafe { bpf_probe_read_kernel(addr) }
}

/// Read a u32 value from a kernel address at a given byte offset.
///
/// # Safety
///
/// `base` must be a valid kernel pointer and `offset` must point to a
/// u32-sized field within the object.
unsafe fn read_u32(base: u64, offset: u64) -> Result<u32, i64> {
    let addr = (base + offset) as *const u32;
    // SAFETY: caller guarantees base+offset points to a valid kernel u32 field.
    unsafe { bpf_probe_read_kernel(addr) }
}

/// Populate common event header fields from current task context.
///
/// Accepts `pid_tgid` to avoid a redundant `bpf_get_current_pid_tgid()` call
/// when the caller has already obtained it (e.g. via [`check_not_self`]).
#[allow(clippy::similar_names)]
fn fill_header(event_type: EventType, pid_tgid: u64, execution_id: u64) -> EventHeader {
    let uid_gid = bpf_get_current_uid_gid();
    let tgid = (pid_tgid >> 32) as u32;
    let tid = pid_tgid as u32;

    // SAFETY: bpf_get_current_task returns a pointer to the current task_struct.
    let task = unsafe { bpf_get_current_task() };

    let ppid = read_ppid(task);
    let euid = read_euid(task);
    let tty_nr = read_tty_nr(task);

    EventHeader::new(
        event_type,
        // SAFETY: bpf_ktime_get_ns has no preconditions.
        unsafe { bpf_ktime_get_ns() },
        tgid,
        ppid,
        tgid,
        tid,
        uid_gid as u32,
        (uid_gid >> 32) as u32,
        euid,
        bpf_get_current_comm().unwrap_or([0u8; 16]),
        tty_nr,
        execution_id,
        // SAFETY: bpf_get_current_cgroup_id has no preconditions.
        unsafe { bpf_get_current_cgroup_id() },
    )
}

/// Read ppid by following task->real_parent->tgid.
fn read_ppid(task: u64) -> u32 {
    // SAFETY: task is from bpf_get_current_task, offsets are BTF-resolved.
    unsafe {
        let Ok(parent) = read_ptr(task, get_offset(offset_idx::TASK_REAL_PARENT)) else {
            return 0;
        };
        read_u32(parent, get_offset(offset_idx::TASK_TGID)).unwrap_or(0)
    }
}

/// Read euid by following task->cred->euid.val.
fn read_euid(task: u64) -> u32 {
    // SAFETY: task is from bpf_get_current_task, offsets are BTF-resolved.
    unsafe {
        let Ok(cred) = read_ptr(task, get_offset(offset_idx::TASK_CRED)) else {
            return 0;
        };
        read_u32(cred, get_offset(offset_idx::CRED_EUID)).unwrap_or(0)
    }
}

/// Read tty index by following task->signal->tty->index.
/// Returns 0 if any pointer in the chain is null (no controlling tty).
fn read_tty_nr(task: u64) -> u32 {
    // SAFETY: task is from bpf_get_current_task, offsets are BTF-resolved.
    unsafe {
        let Ok(signal) = read_ptr(task, get_offset(offset_idx::TASK_SIGNAL)) else {
            return 0;
        };
        let Ok(tty) = read_ptr(signal, get_offset(offset_idx::SIGNAL_TTY)) else {
            return 0;
        };
        if tty == 0 {
            return 0;
        }
        read_u32(tty, get_offset(offset_idx::TTY_INDEX)).unwrap_or(0)
    }
}

/// Unix98 PTY slave major number.
const PTY_SLAVE_MAJOR: u32 = 136;
/// Unix98 PTY master major number.
const PTY_MASTER_MAJOR: u32 = 128;
/// Maximum fd number we'll perform the PTY check on. Keeps the kernel
/// pointer walk bounded; real TTY fds are almost always in the low range.
const MAX_PTY_CHECK_FD: u32 = 255;

/// Check whether fd `fd_num` in the current task points to a PTY device.
///
/// Walks `task->files->fdt->fd[fd_num]->f_inode->i_rdev` and checks the
/// major number against known PTY majors (136 for slave, 128 for master).
///
/// Returns `false` if any pointer in the chain is null or unreadable,
/// or if `fd_num` exceeds [`MAX_PTY_CHECK_FD`].
///
/// # Safety
///
/// Must be called from a BPF tracepoint context where `bpf_get_current_task()`
/// is valid. All offsets must have been resolved from kernel BTF at startup.
#[allow(clippy::inline_always)]
#[inline(always)]
unsafe fn is_pty_fd(fd_num: u32) -> bool {
    if fd_num > MAX_PTY_CHECK_FD {
        return false;
    }
    // SAFETY: bpf_get_current_task has no preconditions in tracepoint context.
    let task = unsafe { bpf_get_current_task() };
    // SAFETY: task is from bpf_get_current_task; all offsets below are
    // BTF-resolved at startup and point to valid kernel struct fields.
    // Each read_ptr/read_u32 call follows a pointer chain through
    // task->files->fdt->fd[n]->f_inode->i_rdev. Null checks guard each step.
    let Ok(files) = (unsafe { read_ptr(task, get_offset(offset_idx::TASK_FILES)) }) else {
        return false;
    };
    if files == 0 {
        return false;
    }
    // SAFETY: files is a valid files_struct pointer (null-checked above).
    let Ok(fdt) = (unsafe { read_ptr(files, get_offset(offset_idx::FILES_FDT)) }) else {
        return false;
    };
    if fdt == 0 {
        return false;
    }
    // SAFETY: fdt is a valid fdtable pointer (null-checked above).
    let Ok(fd_array) = (unsafe { read_ptr(fdt, get_offset(offset_idx::FDT_FD)) }) else {
        return false;
    };
    if fd_array == 0 {
        return false;
    }
    // SAFETY: fd_array is struct file **; fd_num is bounded by MAX_PTY_CHECK_FD.
    let Ok(file_ptr) = (unsafe { read_ptr(fd_array, u64::from(fd_num).wrapping_mul(8)) }) else {
        return false;
    };
    if file_ptr == 0 {
        return false;
    }
    // SAFETY: file_ptr is a valid struct file pointer (null-checked above).
    let Ok(inode) = (unsafe { read_ptr(file_ptr, get_offset(offset_idx::FILE_INODE)) }) else {
        return false;
    };
    if inode == 0 {
        return false;
    }
    // SAFETY: inode is a valid struct inode pointer (null-checked above).
    let Ok(rdev) = (unsafe { read_u32(inode, get_offset(offset_idx::INODE_RDEV)) }) else {
        return false;
    };
    // Extract major number: MAJOR(dev) = (dev >> 8) & 0xFFF
    let major = (rdev >> 8) & 0xFFF;
    major == PTY_SLAVE_MAJOR || major == PTY_MASTER_MAJOR
}

/// Read user-space I/O data into an [`IoEvent`]'s data buffer.
///
/// # Safety
///
/// `event` must point to a valid, writable `IoEvent`. `buf_ptr` must be a
/// valid user-space pointer with at least `byte_count` readable bytes.
#[allow(clippy::inline_always)]
#[inline(always)] // required: BPF verifier rejects non-inlined helpers in some contexts
unsafe fn fill_io_data(
    event: *mut IoEvent,
    buf_ptr: *const u8,
    byte_count: u64,
) -> Result<(), i64> {
    let to_read = if byte_count < MAX_DATA_LEN as u64 {
        byte_count as usize
    } else {
        MAX_DATA_LEN
    };
    // SAFETY: event points to valid writable memory; buf_ptr is a valid user-space pointer.
    unsafe {
        let data = &raw mut (*event).data;
        aya_ebpf::helpers::bpf_probe_read_user_buf(buf_ptr, &mut (&mut (*data))[..to_read])
            .map_err(|_| 1i64)?;
        core::ptr::write(&raw mut (*event).data_len, to_read as u32);
    }
    Ok(())
}

#[tracepoint]
pub fn sys_enter_execve(ctx: TracePointContext) -> u32 {
    match try_sys_enter_execve(&ctx) {
        Ok(()) => 0,
        Err(_) => 1,
    }
}

#[allow(clippy::similar_names)]
fn try_sys_enter_execve(ctx: &TracePointContext) -> Result<(), i64> {
    let Some(pid_tgid) = check_not_self() else {
        return Ok(());
    };

    // ExecEvent is ~5.5KB — too large for the 512-byte BPF stack.
    // Use a per-CPU array as scratch space to build the event.
    let Some(scratch) = EXEC_SCRATCH.get_ptr_mut(0) else {
        return Err(1);
    };

    // SAFETY: scratch points to per-CPU array entry; we write each field
    // individually to stay within BPF stack limits.
    unsafe {
        let hdr = fill_header(EventType::Exec, pid_tgid, 0);
        core::ptr::write(&raw mut (*scratch).header, hdr);
        core::ptr::write(&raw mut (*scratch).retval, 0);

        // Read filename pointer from tracepoint args (offset 16).
        let Ok(filename_ptr): Result<*const u8, _> = ctx.read_at(16) else {
            return Err(1);
        };
        let filename = &raw mut (*scratch).filename;
        (*filename).fill(0);
        let _ = aya_ebpf::helpers::bpf_probe_read_user_str(filename_ptr, &mut *filename);

        // Read argv pointer from tracepoint args (offset 24).
        let Ok(argv_base): Result<*const *const u8, _> = ctx.read_at(24) else {
            return Err(1);
        };

        // Zero the argv array first.
        let argv = &raw mut (*scratch).argv;
        core::ptr::write_bytes(argv.cast::<u8>(), 0, core::mem::size_of_val(&*argv));

        let mut count: u32 = 0;
        for i in 0..MAX_ARGV_COUNT {
            let Ok(arg_ptr) = aya_ebpf::helpers::bpf_probe_read_user(argv_base.add(i)) else {
                break;
            };
            if arg_ptr.is_null() {
                break;
            }
            let dest = &raw mut (*argv)[i];
            let _ = aya_ebpf::helpers::bpf_probe_read_user_str(arg_ptr, &mut *dest);
            count += 1;
        }

        core::ptr::write(&raw mut (*scratch).argc, count);

        // Stash in hash map for sys_exit_execve to pick up.
        let _ = PENDING_EXEC.insert(&pid_tgid, &*scratch, 0);
    }

    Ok(())
}

#[tracepoint]
pub fn sys_exit_execve(ctx: TracePointContext) -> u32 {
    match try_sys_exit_execve(&ctx) {
        Ok(()) => 0,
        Err(_) => 1,
    }
}

fn try_sys_exit_execve(ctx: &TracePointContext) -> Result<(), i64> {
    let pid_tgid = bpf_get_current_pid_tgid();
    let tgid = (pid_tgid >> 32) as u32;

    // SAFETY: retval is at offset 16 in sys_exit_execve tracepoint args.
    let retval: i64 = unsafe { ctx.read_at(16).map_err(|_| 1i64)? };

    // Look up the pending exec event stashed by sys_enter_execve.
    // SAFETY: PENDING_EXEC is a valid BPF hash map and pid_tgid is a valid key.
    let Some(pending) = (unsafe { PENDING_EXEC.get(&pid_tgid) }) else {
        return Err(1);
    };

    // Reserve ring buffer space and copy the pending event with retval set.
    let Some(mut entry) = EVENTS.reserve::<ExecEvent>(0) else {
        let _ = PENDING_EXEC.remove(&pid_tgid);
        return Err(1);
    };
    let event = entry.as_mut_ptr();
    // SAFETY: bpf_ktime_get_ns has no preconditions.
    let execution_id = unsafe { bpf_ktime_get_ns() };

    // SAFETY: pending points to valid hash map entry, event to reserved ringbuf memory.
    unsafe {
        core::ptr::copy_nonoverlapping(pending, event, 1);
        core::ptr::write(&raw mut (*event).header.execution_id, execution_id);
        core::ptr::write(&raw mut (*event).retval, retval);
    }

    entry.submit(0);

    // Track this tgid so I/O events are captured for it.
    if retval >= 0 {
        let _ = EXEC_PIDS.insert(&tgid, &execution_id, 0);
    }

    // Clean up the pending entry.
    let _ = PENDING_EXEC.remove(&pid_tgid);

    Ok(())
}

#[tracepoint]
pub fn sys_enter_exit_group(ctx: TracePointContext) -> u32 {
    match try_sys_enter_exit_group(&ctx) {
        Ok(()) => 0,
        Err(_) => 1,
    }
}

fn try_sys_enter_exit_group(ctx: &TracePointContext) -> Result<(), i64> {
    let Some(pid_tgid) = check_not_self() else {
        return Ok(());
    };
    // SAFETY: error_code is at offset 16 in sys_enter_exit_group tracepoint args.
    let error_code: i64 = unsafe { ctx.read_at(16).map_err(|_| 1i64)? };

    let tgid = (pid_tgid >> 32) as u32;
    // SAFETY: EXEC_PIDS is a valid BPF hash map.
    let execution_id = unsafe { EXEC_PIDS.get(&tgid) }.copied().unwrap_or(0);
    let header = fill_header(EventType::Exit, pid_tgid, execution_id);

    let mut entry = EVENTS.reserve::<ExitEvent>(0).ok_or(1i64)?;
    let event = entry.as_mut_ptr();

    // SAFETY: event points to reserved ringbuf memory with ExitEvent layout.
    unsafe {
        core::ptr::write_bytes(event, 0u8, 1);
        core::ptr::write(&raw mut (*event).header, header);
        core::ptr::write(&raw mut (*event).exit_code, error_code as i32);
    }

    entry.submit(0);

    // Clean up the exec'd PID tracker.
    let _ = EXEC_PIDS.remove(&tgid);
    let _ = PENDING_WRITE.remove(&pid_tgid);
    let _ = PENDING_READ.remove(&pid_tgid);

    Ok(())
}

#[tracepoint]
pub fn sys_enter_write(ctx: TracePointContext) -> u32 {
    match try_sys_enter_write(&ctx) {
        Ok(()) => 0,
        Err(_) => 1,
    }
}

fn try_sys_enter_write(ctx: &TracePointContext) -> Result<(), i64> {
    let Some(pid_tgid) = check_not_self() else {
        return Ok(());
    };
    // SAFETY: fd is at offset 16 in sys_enter_write tracepoint args.
    let fd: u64 = unsafe { ctx.read_at(16).map_err(|_| 1i64)? };
    let fd = fd as u32;

    // Capture fd 1/2 unconditionally (preserves existing behaviour for
    // pipelines, cron jobs, etc.), plus any other fd that points to a PTY.
    // SAFETY: is_pty_fd requires valid tracepoint context (guaranteed here).
    if fd != 1 && fd != 2 && !unsafe { is_pty_fd(fd) } {
        return Ok(());
    }

    // Only capture I/O from processes we've seen exec.
    let tgid = (pid_tgid >> 32) as u32;
    // SAFETY: EXEC_PIDS is a valid BPF hash map.
    if unsafe { EXEC_PIDS.get(&tgid) }.is_none() {
        return Ok(());
    }

    // SAFETY: buf pointer at offset 24 in sys_enter_write tracepoint args.
    let buf_ptr: *const u8 = unsafe { ctx.read_at(24).map_err(|_| 1i64)? };
    // SAFETY: count at offset 32 in sys_enter_write tracepoint args.
    let count: u64 = unsafe { ctx.read_at(32).map_err(|_| 1i64)? };

    let pending = PendingWrite {
        fd,
        _pad: 0,
        buf_ptr: buf_ptr as u64,
        count,
    };

    let _ = PENDING_WRITE.insert(&pid_tgid, &pending, 0);

    Ok(())
}

#[tracepoint]
pub fn sys_exit_write(ctx: TracePointContext) -> u32 {
    match try_sys_exit_write(&ctx) {
        Ok(()) => 0,
        Err(_) => 1,
    }
}

fn try_sys_exit_write(ctx: &TracePointContext) -> Result<(), i64> {
    let pid_tgid = bpf_get_current_pid_tgid();

    // SAFETY: PENDING_WRITE is a valid BPF hash map.
    let Some(pending) = (unsafe { PENDING_WRITE.get(&pid_tgid) }) else {
        return Ok(());
    };

    // SAFETY: ret is at offset 16 in sys_exit_write tracepoint args.
    let ret: i64 = unsafe { ctx.read_at(16).map_err(|_| 1i64)? };
    if ret <= 0 {
        let _ = PENDING_WRITE.remove(&pid_tgid);
        return Ok(());
    }

    let bytes_written = ret as u64;
    let tgid = (pid_tgid >> 32) as u32;
    // SAFETY: EXEC_PIDS is a valid BPF hash map.
    let Some(execution_id) = (unsafe { EXEC_PIDS.get(&tgid) }).copied() else {
        let _ = PENDING_WRITE.remove(&pid_tgid);
        return Ok(());
    };

    let Some(mut entry) = EVENTS.reserve::<IoEvent>(0) else {
        let _ = PENDING_WRITE.remove(&pid_tgid);
        return Err(1);
    };
    let event = entry.as_mut_ptr();

    // SAFETY: event points to reserved ringbuf memory with IoEvent layout.
    unsafe {
        core::ptr::write_bytes(event, 0u8, 1);
        let hdr = fill_header(EventType::Write, pid_tgid, execution_id);
        core::ptr::write(&raw mut (*event).header, hdr);
        core::ptr::write(&raw mut (*event).fd, pending.fd);
        core::ptr::write(&raw mut (*event).count, bytes_written);
        if fill_io_data(event, pending.buf_ptr as *const u8, bytes_written).is_err() {
            entry.discard(0);
            let _ = PENDING_WRITE.remove(&pid_tgid);
            return Err(1);
        }
    }

    entry.submit(0);
    let _ = PENDING_WRITE.remove(&pid_tgid);
    Ok(())
}

#[tracepoint]
pub fn sys_enter_read(ctx: TracePointContext) -> u32 {
    match try_sys_enter_read(&ctx) {
        Ok(()) => 0,
        Err(_) => 1,
    }
}

fn try_sys_enter_read(ctx: &TracePointContext) -> Result<(), i64> {
    let Some(pid_tgid) = check_not_self() else {
        return Ok(());
    };
    // SAFETY: fd at offset 16, buf at offset 24, count at offset 32.
    let fd: u64 = unsafe { ctx.read_at(16).map_err(|_| 1i64)? };
    let fd = fd as u32;

    // Capture fd 0 unconditionally (preserves existing behaviour),
    // plus any other fd that points to a PTY.
    // SAFETY: is_pty_fd requires valid tracepoint context (guaranteed here).
    if fd != 0 && !unsafe { is_pty_fd(fd) } {
        return Ok(());
    }

    // Only capture I/O from processes we've seen exec.
    let tgid = (pid_tgid >> 32) as u32;
    // SAFETY: EXEC_PIDS is a valid BPF hash map.
    if unsafe { EXEC_PIDS.get(&tgid) }.is_none() {
        return Ok(());
    }

    // SAFETY: buf pointer at offset 24 in sys_enter_read tracepoint args.
    let buf_ptr: u64 = unsafe { ctx.read_at(24).map_err(|_| 1i64)? };
    // SAFETY: count at offset 32 in sys_enter_read tracepoint args.
    let count: u64 = unsafe { ctx.read_at(32).map_err(|_| 1i64)? };

    let pending = PendingRead {
        fd,
        _pad: 0,
        buf_ptr,
        count,
    };

    let _ = PENDING_READ.insert(&pid_tgid, &pending, 0);

    Ok(())
}

#[tracepoint]
pub fn sys_exit_read(ctx: TracePointContext) -> u32 {
    match try_sys_exit_read(&ctx) {
        Ok(()) => 0,
        Err(_) => 1,
    }
}

fn try_sys_exit_read(ctx: &TracePointContext) -> Result<(), i64> {
    let pid_tgid = bpf_get_current_pid_tgid();

    // SAFETY: PENDING_READ is a valid BPF hash map.
    let Some(pending) = (unsafe { PENDING_READ.get(&pid_tgid) }) else {
        return Ok(());
    };

    // SAFETY: ret is at offset 16 in sys_exit_read tracepoint args.
    let ret: i64 = unsafe { ctx.read_at(16).map_err(|_| 1i64)? };

    // Negative return means error — no data was read.
    if ret <= 0 {
        let _ = PENDING_READ.remove(&pid_tgid);
        return Ok(());
    }

    let bytes_read = ret as u64;
    let buf_ptr = pending.buf_ptr as *const u8;
    let fd = pending.fd;
    let tgid = (pid_tgid >> 32) as u32;
    // SAFETY: EXEC_PIDS is a valid BPF hash map.
    let Some(execution_id) = (unsafe { EXEC_PIDS.get(&tgid) }).copied() else {
        let _ = PENDING_READ.remove(&pid_tgid);
        return Ok(());
    };

    // Reserve ring buffer space and write event in-place.
    let Some(mut entry) = EVENTS.reserve::<IoEvent>(0) else {
        let _ = PENDING_READ.remove(&pid_tgid);
        return Err(1);
    };
    let event = entry.as_mut_ptr();

    // SAFETY: event points to reserved ringbuf memory with IoEvent layout.
    unsafe {
        core::ptr::write_bytes(event, 0u8, 1);
        let hdr = fill_header(EventType::Read, pid_tgid, execution_id);
        core::ptr::write(&raw mut (*event).header, hdr);
        core::ptr::write(&raw mut (*event).fd, fd);
        core::ptr::write(&raw mut (*event).count, bytes_read);
        if fill_io_data(event, buf_ptr, bytes_read).is_err() {
            entry.discard(0);
            let _ = PENDING_READ.remove(&pid_tgid);
            return Err(1);
        }
    }

    entry.submit(0);

    let _ = PENDING_READ.remove(&pid_tgid);

    Ok(())
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}
